# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weatherData',
            field=models.TextField(max_length=100),
        ),
    ]
