# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=100)),
                ('lastName', models.TextField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('crisisType', models.TextField(max_length=10)),
                ('crisisState', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherData', models.TextField(max_length=100)),
            ],
        ),
    ]
