# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_System', '0002_auto_20170404_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
