# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_System', '0004_auto_20170404_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisisstate',
            old_name='crisisStateData',
            new_name='crisisState',
        ),
    ]
