# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_System', '0005_auto_20170405_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='assistanceType',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
